### ISSUE TITLE
Unable to use GPU alnog with python 2

### ISSUE THREAD

**Issue by Akshay0724** [gw0/docker-keras-full#3]
I have build the docker image and given this command
``$ docker run -it $(ls /dev/nvidia* | xargs -I{} echo '--device={}') -p=6006:6006 -p=8888:8888 -v=/srv/notebooks:/srv gw000/keras-full``

everthing is working but GPU is not used when I executed this theano code
```
from theano import function, config, shared, tensor
import numpy
import time

vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')

```

I have installed the gpu driver and gpu is working fine with the other container of deep learning.

I am using Nvidia GTX 1080 GPU 
processor i7 7th gen 8 cores.
OS Ubuntu 16.04

My question is that how I can use GPU version of keras with along with python 2 on this container?

Thanks

**Comment by gw0** [comment]
Sorry for the delay...

Probably there is an issue with incompatible versions of driver and library. Have you tried to inject also the libraries from your host OS into the container? I have found that this usually works

```
docker run -it --rm $(ls /dev/nvidia* | xargs -I{} echo '--device={}') $(ls /usr/lib/*-linux-gnu/{libcuda,libnvidia}* | xargs -I{} echo '-v {}:{}:ro') -p=6006:6006 -p=8888:8888 -v=/srv/notebooks:/srv gw000/keras-full
```

Does this work?

If not, which other container works?

*docker-keras-full* contains Python 2 and Python 3. Both include Keras, TensorFlow, Theano and CNTK (version that will soon be released). In case the GPU is detected it is used, if not it falls back to CPU. Therefore if CPU is used, something is wrong with GPU detection (probably mismatch between kernel driver and library).

**Comment by gw0** [comment]
Closing, because it should work if used correctly. If there are still issues, please, open the issue again.
