### ISSUE TITLE
want to install something in container

### ISSUE THREAD

**Issue by evoup** [gw0/docker-keras-full#6]
I`d like to install some ubuntu package in container，but need root privilege，so what is the root passeword?
Thanks

**Comment by evoup** [comment]
hello，already find  the way.
docker exec -u 0 -it keras-full /bin/bash

thank you all the same!

**Comment by gw0** [comment]
Yes, for one-time changes in Docker containers you can always override the UID and execution command.

But usually you want to install new packages in a persistent manner. This is done by writing you own `Dockerfile` which extends this image. For example see how this can is done with a similar image <https://github.com/gw0/docker-keras#usage>.
