### ISSUE TITLE
jupyter password

### ISSUE THREAD

**Issue by sunilchinnahalli** [gw0/docker-keras-full#8]
am not getting a password or token to enter

I didn't understand where to run the commands to get password or token please help

**Comment by gw0** [comment]
If you look in the source code of `Dockerfile`, you see that the following code is currently uncommented. As the comment describes, the password and token are `keras`.

```
# password and token authentication (password and token: keras)
ENV PASSWD='sha1:98b767162d34:8da1bc3c75a0f29145769edc977375a373407824'
ENV TOKEN='keras'
```
